ayulalms/urls.py
# coding=utf-8
"""ayulalms URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
import debug_toolbar
import sys
from django.conf.urls import include

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView,  \
     PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView,\
    PasswordChangeDoneView
from django.urls import path
from django.views.debug import technical_500_response
from django.conf import urls
from accounts.view import SignUpView, home

urlpatterns = (
    path('__debug__/', include(debug_toolbar.urls)),
    path('', home, name='home'),
    path('adminact/', include('adminactions.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path('discussion/', include('discussion.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),

    path('reset/', PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    path('reset/done/',PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/complete/',PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    path('settings/password/done/', PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
)

# def handler500(request):
#     return technical_500_response(request, *sys.exc_info())


# urls.handler500 =  handler500

instructor/urls.py
from django.urls import include, path
from course.views import CourseListView, CourseUpdateView, CourseDeleteView, TopicListView, \
    TopicCreateView, TopicUpdateView, TopicDeleteView
from instructor.views import QuizListView, QuizCreateView, QuizUpdateView, QuizDeleteView, QuizResultsView, \
    question_add, question_change, QuestionDeleteView, CourseDetailView

urlpatterns = [
    # path('', classroom.home, name='home'),
    path('instructor/', include(([
        path('', CourseListView.as_view(), name='course_change_list'),
        path('course/<int:pk>/', CourseUpdateView.as_view(), name='course_change'),
        path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),
        path('coursedetail/<int:course_pk>/', CourseDetailView.as_view(), name='course_detail'),

        path('topic', TopicListView.as_view(), name='topic_change_list'),
        path('topic/add/<int:course_pk>/', TopicCreateView.as_view(), name='topic_add'),
        path('topic/<int:pk>/', TopicUpdateView.as_view(), name='topic_change'),
        path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name='topic_delete'),

        path('quiz', QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/<int:course_pk>/', QuizCreateView.as_view(), name='quiz_add'),
        # path('quiz/add/<int:course_pk>/', quizcreate, name='quiz_add'),
        path('quiz/<int:pk>/', QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', QuestionDeleteView.as_view(), name='question_delete'),
    ], 'instructor'), namespace='instructor')),
]

student/urls.py
# coding=utf-8
from django.urls import include, path
from course.views import CourseDetailView
from student.views import QuizListView, TakenQuizListView, take_quiz, CourseListView, course_registration, \
    RegisteredCourseListView

urlpatterns = [
    path('student/', include(([
        path('', CourseListView.as_view(), name='course_change_list'),
        path('viewcourse/<int:course_pk>/', CourseDetailView.as_view(), name='course_detail'),
        path('registered/course', RegisteredCourseListView.as_view(), name='registered_course_list'),
        path('register/<int:course_pk>/', course_registration, name='register_course'),
        path('quiz', QuizListView.as_view(), name='quiz_list'),
        path('taken/', TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', take_quiz, name='take_quiz'),
    ], 'student'), namespace='student')),
]

templates/externals/admin_dashboard.html
{% extends 'externals/base.html' %}

          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Admin Dashboard</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
              <div class="row bg-white has-shadow">
                <!-- Item -->
                <div class="col-xl-3 col-sm-6">
                  <div class="item d-flex align-items-center">
                    <div class="icon bg-violet"><i class="icon-user"></i></div>
                    <div class="title"><span>New<br>Clients</span>
                      <div class="progress">
                        <div role="progressbar" style="width: 25%; height: 4px;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-violet"></div>
                      </div>
                    </div>
                    <div class="number"><strong>25</strong></div>
                  </div>
                </div>
                <!-- Item -->
                <div class="col-xl-3 col-sm-6">
                  <div class="item d-flex align-items-center">
                    <div class="icon bg-red"><i class="icon-padnote"></i></div>
                    <div class="title"><span>Work<br>Orders</span>
                      <div class="progress">
                        <div role="progressbar" style="width: 70%; height: 4px;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-red"></div>
                      </div>
                    </div>
                    <div class="number"><strong>70</strong></div>
                  </div>
                </div>
                <!-- Item -->
                <div class="col-xl-3 col-sm-6">
                  <div class="item d-flex align-items-center">
                    <div class="icon bg-green"><i class="icon-bill"></i></div>
                    <div class="title"><span>New<br>Invoices</span>
                      <div class="progress">
                        <div role="progressbar" style="width: 40%; height: 4px;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-green"></div>
                      </div>
                    </div>
                    <div class="number"><strong>40</strong></div>
                  </div>
                </div>
                <!-- Item -->
                <div class="col-xl-3 col-sm-6">
                  <div class="item d-flex align-items-center">
                    <div class="icon bg-orange"><i class="icon-check"></i></div>
                    <div class="title"><span>Open<br>Cases</span>
                      <div class="progress">
                        <div role="progressbar" style="width: 50%; height: 4px;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-orange"></div>
                      </div>
                    </div>
                    <div class="number"><strong>50</strong></div>
                  </div>
                </div>
              </div>
            </div>
          </section>

    <section class="dashboard-header">
            <div class="container-fluid">
              <div class="row">
                <!-- Statistics -->
                <div class="statistics col-md-4 col-12">
                  <div class="statistic d-flex align-items-center bg-white has-shadow">
                    <div class="icon bg-red"><i class="fa fa-tasks"></i></div>
                    <div class="text"><strong>234</strong><br><small>Applications</small></div>
                  </div>
                  <div class="statistic d-flex align-items-center bg-white has-shadow">
                    <div class="icon bg-green"><i class="fa fa-calendar-o"></i></div>
                    <div class="text"><strong>152</strong><br><small>Interviews</small></div>
                  </div>
                  <div class="statistic d-flex align-items-center bg-white has-shadow">
                    <div class="icon bg-orange"><i class="fa fa-paper-plane-o"></i></div>
                    <div class="text"><strong>147</strong><br><small>Forwards</small></div>
                  </div>
                </div>
                <!-- Line Chart            -->


              </div>
            </div>
          </section>

    {% endblock content %}

templates/externals/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Learning Management System{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'externals/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'externals/vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static 'externals/css/fontastic.css' %}">
    <!-- Google fonts - Poppins -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'externals/css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'externals/css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'externals/img/favicon.ico ' %}">
      {% if user.is_authenticated and user.is_instructor %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/instructor.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/students.css' %}">
    {% endif %}
  </head>
  <body>
    <div class="page">
      <!-- Main Navbar-->
      <header class="header">
        <nav class="navbar">
          <!-- Search Box-->

          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <!-- Navbar Header-->
              <div class="navbar-header">
                <!-- Navbar Brand --><a href="index.html" class="navbar-brand d-none d-sm-inline-block">
                  <div class="brand-text d-none d-lg-inline-block"><span>AYULLA </span><strong>LMS</strong></div>
                  <div class="brand-text d-none d-sm-inline-block d-lg-none"><strong>BD</strong></div></a>
                <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
              </div>
              <!-- Navbar Menu -->
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">

                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link logout"> <span class="d-none d-sm-inline">Logout</span><i class="fa fa-sign-out"></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="page-content d-flex align-items-stretch">
        <!-- Side Navbar -->
        <nav class="side-navbar">
          <!-- Sidebar Header-->
          <div class="sidebar-header d-flex align-items-center">
            <div class="avatar"><img src="{% static 'externals/img/avatar-1.jpg' %}" alt="..." class="img-fluid rounded-circle"></div>
            <div class="title">
              <h1 class="h4">{{ user.username }}</h1>
              {% if user.is_instructor %}
                <p>Course Instructor</p>
                {% elif user.is_student %}
                <p>Student</p>
                {% elif user.is_staff %}
                <p>Staff</p>
                {% endif %}
            </div>
          </div>
          <!-- Sidebar Navidation Menus-->


            {% if user.is_staff %}


            <!-- Admin Side Panel -->
              <ul class="list-unstyled">
                        <li class="active"><a href="{% url 'admin_home' %}"> <i class="icon-home"></i>Home </a></li>
                        <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Accounts Summary </a>
                          <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                            <li><a href="{% url 'instructor_accounts' %}">Instructors Account</a></li>
                            <li><a href="{% url 'student_accounts' %}">Students Account</a></li>
                            <li><a href="{% url 'observer_accounts' %}">Observers Account</a></li>
                          </ul>
                        </li>
                        <li><a href="#exampledropdownDropdown1" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Create Accounts </a>
                          <ul id="exampledropdownDropdown1" class="collapse list-unstyled ">
                            <li><a href="{% url 'instructor_signup' %}">Add Instructor</a></li>
                            <li><a href="{% url 'student_signup' %}">Add Student</a></li>
                            <li><a href="{% url 'guest_signup' %}">Add Observer</a></li>
                          </ul>
                        </li>
                        <li><a href="#exampledropdownDropdown2" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Courses </a>
                          <ul id="exampledropdownDropdown2" class="collapse list-unstyled ">
                            <li><a href="{% url 'admin_list_courses' %}">View Courses</a></li>
                            <li><a href="{% url 'admin_create_courses' %}">Add Course</a></li>
                            <li><a href="{% url 'admin_assign_courses' %}">Assign Course To Instructors</a></li>
                          </ul>
                        </li>
                 <li><a href="{% url 'discussion_home' %}"> <i class="icon-interface-windows"></i>Discussions </a></li>
              </ul>
            {% endif %}





                <!-- Instructor Side Panel -->
        {% if user.is_instructor %}
            <ul class="list-unstyled">
                    <li class="active"><a href="{% url 'home' %}"> <i class="icon-home"></i>Home </a></li>

                        <li><a href="#exampledropdownDropdown2" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Courses </a>
                          <ul id="exampledropdownDropdown2" class="collapse list-unstyled ">
                            <li><a href="{% url 'instructor:course_change_list' %}">View Courses</a></li>

                          </ul>
                        </li>
                    <li><a href="{% url 'instructor:topic_change_list' %}"> <i class="icon-interface-windows"></i>Course Topics </a></li>
                    <li><a href="{% url 'instructor:quiz_change_list' %}"> <i class="icon-interface-windows"></i>My Quizzes </a></li>
                    <li><a href="#"> <i class="icon-interface-windows"></i>Course Assignments </a></li>

                    <li><a href="#exampledropdownDropdown5" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Discussions </a>
                      <ul id="exampledropdownDropdown5" class="collapse list-unstyled ">
                        <li><a href="{% url 'new_board' %}">Create Board</a></li>
                        <li><a href="{% url 'discussion_home' %}">View Discussions</a></li>

                      </ul>
                    </li>
                </ul>
        {% endif %}
            <!-- Student Side Panel -->
        {% if user.is_student %}
             <ul class="list-unstyled">
                    <li class="active"><a href="{% url 'student:course_change_list' %}"> <i class="icon-home"></i>Courses </a></li>
                    <li><a href="{% url 'student:registered_course_list' %}"> <i class="icon-grid"></i>Registered Course</a></li>
                    <li><a href="{% url 'student:quiz_list' %}"> <i class="fa fa-bar-chart"></i>Quizzes </a></li>
                    <li class=""><a href="{% url 'discussion_home' %}"> <i class="icon-home"></i>Discussions </a></li>
                    <li><a href="#exampledropdownDropdown9" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Assignments </a>
                      <ul id="exampledropdownDropdown9" class="collapse list-unstyled ">
                        <li><a href="#">Course Assignments</a></li>
                        <li><a href="#">Reviews</a></li>
                      </ul>
                    </li>


             </ul>
        {% endif %}
            <!-- Observer Side Panel -->
        {% if user.is_observer %}
             <ul class="list-unstyled">
                    <li class="active"><a href="index.html"> <i class="icon-home"></i>Home </a></li>
                    <li><a href="tables.html"> <i class="icon-grid"></i>Tables </a></li>
                    <li><a href="charts.html"> <i class="fa fa-bar-chart"></i>Charts </a></li>
                    <li><a href="forms.html"> <i class="icon-padnote"></i>Forms </a></li>
                    <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
                      <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                      </ul>
                    </li>
                    <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
                      <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                      </ul>
                    </li>
                    <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
                      <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                        <li><a href="#">Page</a></li>
                      </ul>
                    </li>
                    <li><a href="login.html"> <i class="icon-interface-windows"></i>Login page </a></li>
            </ul>
        {% endif %}
        </nav>
        <div class="content-inner">
        <header class="page-header">
          {% block header %}

          {% endblock header %}
          </header>

            {% block content %}




            {% endblock content %}

        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'externals/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'externals/vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'externals/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'externals/vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'externals/vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'externals/vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'externals/js/charts-home.js' %}"></script>
    {% block javascript %} {% endblock javascript %}
    <!-- Main File-->
    <script src="{% static 'externals/js/front.js' %}"></script>
  </body>
</html>

templates/externals/course_list_admin.html
{% extends 'externals/base.html' %}


          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Courses List</h2>
            </div>
          {% endblock header %}
{% block content %}
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
  <nav aria-label="breadcrumb">
  {% if request.user.is_instructor %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Available Courses</li>
    </ol>
  {% endif %}
  {% if request.user.is_instructor %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Courses</li>
    </ol>
  {% endif %}
  </nav>

   {% if request.user.is_student %}
  <h2 class="mb-3">My Courses</h2>
  <a href="{% url 'student:registered_course_list' %}" class="btn btn-primary mb-3" role="button">View Registered Courses</a>
    {% endif %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
            {% if request.user.is_instructor %}
          <th>Created</th>
            {% endif %}
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for course in courses %}
          <tr>

            <td class="align-middle"><a href="{% url 'admin_view_courses' course.pk %}">{{ course.title }}</a></td>
            <td class="align-middle">{{ course.description|truncatechars:15}}</td>
              {% if request.user.is_instructor %}
            <td class="align-middle">{{ course.created }}</td>
              {% endif %}
            <td class="text-right">
                {% if request.user.is_instructor %}
              <a href="{% url 'instructor:topic_add' course.pk %}" class="btn btn-primary">Add Topics</a>
              <a href="{% url 'instructor:quiz_add' course.pk %}" class="btn btn-primary">Create Quiz</a>
{#              <a href="{% url 'student:register_course' course.pk %}" class="btn btn-primary">Register Students</a>#}
            {% endif %}
            </td>

          </tr>
        {% empty %}
            {% if request.user.is_instructor %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any course yet.</td>
          </tr>
            {% endif %}
            {% if request.user.is_student %}
            <tr>
                <td class="bg-light text-center font-italic" colspan="5">There are no course available.</td>
            </tr>
            {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
            </div>
        </section>
{% endblock %}