ayulalms/urls.py
# coding=utf-8
"""ayulalms URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
import debug_toolbar
import sys
from django.conf.urls import include

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView,  \
     PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView,\
    PasswordChangeDoneView
from django.urls import path
from django.views.debug import technical_500_response
from django.conf import urls
from accounts.view import SignUpView, home

urlpatterns = (
    path('__debug__/', include(debug_toolbar.urls)),
    path('', home, name='home'),
    path('adminact/', include('adminactions.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path('discussion/', include('discussion.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),

    path('reset/', PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    path('reset/done/',PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/complete/',PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    path('settings/password/done/', PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
)

# def handler500(request):
#     return technical_500_response(request, *sys.exc_info())


# urls.handler500 =  handler500

instructor/urls.py
from django.urls import include, path
from course.views import CourseListView, CourseUpdateView, CourseDeleteView, TopicListView, \
    TopicCreateView, TopicUpdateView, TopicDeleteView
from instructor.views import QuizListView, QuizCreateView, QuizUpdateView, QuizDeleteView, QuizResultsView, \
    question_add, question_change, QuestionDeleteView, CourseDetailView

urlpatterns = [
    # path('', classroom.home, name='home'),
    path('instructor/', include(([
        path('', CourseListView.as_view(), name='course_change_list'),
        path('course/<int:pk>/', CourseUpdateView.as_view(), name='course_change'),
        path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),
        path('coursedetail/<int:course_pk>/', CourseDetailView.as_view(), name='course_detail'),

        path('topic', TopicListView.as_view(), name='topic_change_list'),
        path('topic/add/<int:course_pk>/', TopicCreateView.as_view(), name='topic_add'),
        path('topic/<int:pk>/', TopicUpdateView.as_view(), name='topic_change'),
        path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name='topic_delete'),

        path('quiz', QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/<int:course_pk>/', QuizCreateView.as_view(), name='quiz_add'),
        # path('quiz/add/<int:course_pk>/', quizcreate, name='quiz_add'),
        path('quiz/<int:pk>/', QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', QuestionDeleteView.as_view(), name='question_delete'),
    ], 'instructor'), namespace='instructor')),
]

student/urls.py
# coding=utf-8
from django.urls import include, path
from course.views import CourseDetailView
from student.views import QuizListView, TakenQuizListView, take_quiz, CourseListView, course_registration, \
    RegisteredCourseListView

urlpatterns = [
    path('student/', include(([
        path('', CourseListView.as_view(), name='course_change_list'),
        path('viewcourse/<int:course_pk>/', CourseDetailView.as_view(), name='course_detail'),
        path('registered/course', RegisteredCourseListView.as_view(), name='registered_course_list'),
        path('register/<int:course_pk>/', course_registration, name='register_course'),
        path('quiz', QuizListView.as_view(), name='quiz_list'),
        path('taken/', TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', take_quiz, name='take_quiz'),
    ], 'student'), namespace='student')),
]

student/models.py
# coding=utf-8
from django.db import models
from accounts.models import User
from course.models import Course
from quiz.models import Answer


class StudentProfile(models.Model):
    """
    Used to represent fields specific to the student user
    it's user field has a one to one relationship with the  User class
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='student')
    school_number = models.CharField(max_length=20, null=True, blank=True)
    photo = models.FileField(upload_to='tutor', null=True, blank=True)
    designation = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    student_quizzes = models.ManyToManyField('quiz.Quiz', through='StudentTakenQuiz')
    course = models.ManyToManyField(Course)

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    class Meta:
        verbose_name_plural = 'Student'

    def __str__(self):
        return self.user.username


class StudentCourses(models.Model):
    student = models.ForeignKey(StudentProfile, null=True, on_delete=models.CASCADE)
    student_course = models.ManyToManyField(Course)

    class Meta:
        verbose_name_plural = 'Student Courses'


class StudentTakenQuiz(models.Model):
    student = models.ForeignKey('student.StudentProfile', on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey('quiz.Quiz', on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey('quiz.Answer', on_delete=models.CASCADE, related_name='+')

student/views.py
# coding=utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from accounts.decorators import student_required, instructor_required
from course.models import Course
from quiz.forms import TakeQuizForm
from quiz.models import Quiz
from student.models import StudentTakenQuiz, StudentProfile


@method_decorator([login_required], name='dispatch')
class CourseListView(ListView):
    """
        Returns a list of all available courses on the platform
    """
    model = Course
    ordering = ('title', )
    context_object_name = 'courses'
    template_name = 'course_change_list.html'

    def get_queryset(self):
        """
        Returns queryset to be used for displaying data on template
        :return:
        """
        student = get_object_or_404(StudentProfile, user=self.request.user).course.values('title')
        queryset = Course.objects.exclude(studentprofile__course__title__in=student)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class RegisteredCourseListView(ListView):
    """
        Returns a list of all available courses on the platform
    """
    model = Course
    ordering = ('title', )
    context_object_name = 'unregistered_courses'
    template_name = 'student_registered_courses.html'

    def get_context_data(self, **kwargs):
        """
        Passes the list of students registered courses as a context to the view
        :param kwargs:
        :return:
        """
        student = get_object_or_404(StudentProfile, user=self.request.user)
        student_registered_courses = student.course.all()
        kwargs['student_registered_courses'] = student_registered_courses
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        """
        Returns queryset to be used for displaying data on template
        :return:
        """
        student = get_object_or_404(StudentProfile, user=self.request.user).course.values('title')
        queryset = Course.objects.exclude(studentprofile__course__title__in=student)
        return queryset


@login_required
@instructor_required
def course_registration(request, course_pk):
    """
    Handles Student Course Registration
    Returns a context containing list of courses registered by student and  a list of
    students un-registered courses.
    Also ensures that a student cannot register a course twice
    :param request:
    :param course_pk:
    :return:
    """
    course = get_object_or_404(Course, pk=course_pk)
    student = get_object_or_404(StudentProfile, user=request.user)
    student_registered_courses = student.course.all()
    unregistered_courses = Course.objects.exclude(studentprofile__course__in=student_registered_courses)

    if course in student_registered_courses:
        messages.error(request, "This Course {0} has been registered already ".format(course.title))
        return render(request, 'student_registered_courses.html', {'student_registered_courses': student_registered_courses, \
                                                                   'unregistered_courses': unregistered_courses})
    #register student to course
    student.course.add(course)
    messages.success(request, "The course {0} was successfully added".format(course.title))
    return render(request, 'student_registered_courses.html', {'student_registered_courses': student_registered_courses, \
                                                                   'unregistered_courses':unregistered_courses})




@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'quiz_list.html'

    def get_queryset(self):
        student = get_object_or_404(StudentProfile, user=self.request.user)
        student_courses = student.course.values_list('pk', flat=True)
        taken_quizzes = student.student_quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(course__in=student_courses) \
            .exclude(pk__in=taken_quizzes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = StudentTakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'taken_quiz_list.html'

    def get_queryset(self):
        student = get_object_or_404(StudentProfile, user=self.request.user)
        queryset = student.taken_quizzes \
            .select_related('quiz', 'quiz__course') \
            .order_by('quiz__name')
        return queryset


@login_required
@student_required
def take_quiz(request, pk):

    quiz = get_object_or_404(Quiz, pk=pk)
    student = get_object_or_404(StudentProfile, user=request.user)

    if student.student_quizzes.filter(pk=pk).exists():
        messages.error(request, "You have already taken this quiz")
        return redirect('student:taken_quiz_list')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(quiz).exists():
                    return redirect('student:take_quiz', pk)
                else:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    score = round((correct_answers / total_questions) * 100.0, 2)
                    StudentTakenQuiz.objects.create(student=student, quiz=quiz, score=score)
                    if score < 50.0:
                        messages.warning(request, 'Better luck next time! Your score for the quiz %s was %s.' % (quiz.name, score))
                    else:
                        messages.success(request, 'Congratulations! You completed the quiz %s with success! You scored %s points.' % (quiz.name, score))
                    return redirect('student:quiz_list')
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'progress': progress
    })

student/templates/_header.html
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'student:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'student:taken_quiz_list' %}">Taken</a>
  </li>
</ul>

student/templates/quiz_list.html
{% extends 'externals/base.html' %}

         {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom">Quiz List</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

  {% include '_header.html' with active='new' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Course</th>
          <th>Length</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.course }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'student:take_quiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">There are no available quiz for you now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
            </div>
    </section>
{% endblock %}

student/templates/student_registered_courses.html
{% extends 'externals/base.html' %}

         {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Course Summary</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

  <nav aria-label="breadcrumb">
  {% if request.user.is_instructor %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Courses</li>
    </ol>
  {% endif %}
  </nav>

 <h2 class="mb-3">Un-Registered Courses</h2>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
            {% if request.user.is_instructor %}
          <th>Created</th>
            {% endif %}
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for course in unregistered_courses %}
          <tr>

            <td class="align-middle">{{ course.title }}</td>
            <td class="align-middle">{{ course.description|truncatewords:12}}</td>
              {% if request.user.is_instructor %}
            <td class="align-middle">{{ course.created }}</td>
              {% endif %}
            <td class="text-right">
            {% if request.user.is_student %}
{#              <a href="{% url 'student:register_course' course.pk %}" class="btn btn-primary">Register Course</a>#}
            {% endif %}
            </td>

          </tr>
        {% empty %}
            {% if request.user.is_instructor %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any course yet.</td>
          </tr>
            {% endif %}
            {% if request.user.is_student %}
            <tr>
                <td class="bg-light text-center font-italic" colspan="5">There are no course available.</td>
            </tr>
            {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
     <h2 class="mb-3">My Registered Courses</h2>
    <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>



        </tr>
      </thead>
      <tbody>
        {% for course in student_registered_courses %}
          <tr>

            <td class="align-middle">{{ course.title }}</td>
            <td class="align-middle">{{ course.description |truncatewords:12}}</td>
            <td class="text-right">
               <a href="{% url 'student:course_detail' course.pk %}" class="btn btn-primary">Take Course</a>

            </td>
          </tr>
        {% empty %}
            {% if request.user.is_student %}
            <tr>
                <td class="bg-light text-center font-italic" colspan="5">You have not registered any course yet.</td>
            </tr>
            {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
            </div>
    </section>
{% endblock %}

student/templates/take_course.html
{% extends 'externals/base.html' %}
          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom">{{ course.title }} Details</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">


  <h2 class="mb-3">{{ course.title }}</h2>
<div class="panel panel-primary">
  <div class="panel-heading">Course Title</div>
  <div class="panel-body">
    {{ course.title }}
  </div>
<div class="panel panel-primary">
  <div class="panel-heading">Course Description</div>
  <div class="panel-body">
    {{ course.description }}
  </div>
<div class="panel panel-primary">
  <div class="panel-heading">Course Instructors</div>
  <div class="panel-body">
    {% for instructor in instructors %}
        {{ instructor.user.username }}
      {% endfor %}
  <h1>Topics</h1>
      {% for topic in topics %}
        {{ topic.topic_title }}
      {% endfor %}
  </div>
</div>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Course</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'instructor:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.course.title }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="text-right">
{#              <a href="{% url 'instructor:quiz_results' quiz.pk %}" class="btn btn-primary">View results</a>#}
                <a href="{% url 'instructor:quiz_change' quiz.pk %}" class="btn btn-primary">Edit Quiz</a>

            </td>
          </tr>
        {% empty %}
            {% if request.user.is_instructor %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any quiz yet.</td>
          </tr>
            {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
            </div>
    </section>
{% endblock %}

student/templates/take_quiz_form.html
{% extends 'externals/base.html' %}

{% load crispy_forms_tags %}
         {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Admin Dashboard</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }}</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
        {% if submit_button %}
    <button type="submit" class="btn btn-primary">Assign →</button>
         {% else %}
  <button type="submit" class="btn btn-primary">Next →</button>
        {% endif %}
  </form>
            </div>
    </section>
{% endblock %}

student/templates/taken_quiz_list.html
{% extends 'externals/base.html' %}

         {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom">Taken Quiz</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

  {% include '_header.html' with active='taken' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Course</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.quiz.course }}</td>
            <td>{{ taken_quiz.score }}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
            </div>
    </section>
{% endblock %}