ayulalms/urls.py
# coding=utf-8
"""ayulalms URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
import debug_toolbar
import sys
from django.conf.urls import include

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView,  \
     PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView,\
    PasswordChangeDoneView
from django.urls import path
from django.views.debug import technical_500_response
from django.conf import urls
from accounts.view import SignUpView, home

urlpatterns = (
    path('__debug__/', include(debug_toolbar.urls)),
    path('', home, name='home'),
    path('adminact/', include('adminactions.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path('discussion/', include('discussion.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),

    path('reset/', PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    path('reset/done/',PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/complete/',PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    path('settings/password/done/', PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
)

# def handler500(request):
#     return technical_500_response(request, *sys.exc_info())


# urls.handler500 =  handler500

instructor/urls.py
from django.urls import include, path
from course.views import CourseListView, CourseUpdateView, CourseDeleteView, TopicListView, \
    TopicCreateView, TopicUpdateView, TopicDeleteView
from instructor.views import QuizListView, QuizCreateView, QuizUpdateView, QuizDeleteView, QuizResultsView, \
    question_add, question_change, QuestionDeleteView, CourseDetailView

urlpatterns = [
    # path('', classroom.home, name='home'),
    path('instructor/', include(([
        path('', CourseListView.as_view(), name='course_change_list'),
        path('course/<int:pk>/', CourseUpdateView.as_view(), name='course_change'),
        path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),
        path('coursedetail/<int:course_pk>/', CourseDetailView.as_view(), name='course_detail'),

        path('topic', TopicListView.as_view(), name='topic_change_list'),
        path('topic/add/<int:course_pk>/', TopicCreateView.as_view(), name='topic_add'),
        path('topic/<int:pk>/', TopicUpdateView.as_view(), name='topic_change'),
        path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name='topic_delete'),

        path('quiz', QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/<int:course_pk>/', QuizCreateView.as_view(), name='quiz_add'),
        # path('quiz/add/<int:course_pk>/', quizcreate, name='quiz_add'),
        path('quiz/<int:pk>/', QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', QuestionDeleteView.as_view(), name='question_delete'),
    ], 'instructor'), namespace='instructor')),
]

student/urls.py
# coding=utf-8
from django.urls import include, path
from course.views import CourseDetailView
from student.views import QuizListView, TakenQuizListView, take_quiz, CourseListView, course_registration, \
    RegisteredCourseListView

urlpatterns = [
    path('student/', include(([
        path('', CourseListView.as_view(), name='course_change_list'),
        path('viewcourse/<int:course_pk>/', CourseDetailView.as_view(), name='course_detail'),
        path('registered/course', RegisteredCourseListView.as_view(), name='registered_course_list'),
        path('register/<int:course_pk>/', course_registration, name='register_course'),
        path('quiz', QuizListView.as_view(), name='quiz_list'),
        path('taken/', TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', take_quiz, name='take_quiz'),
    ], 'student'), namespace='student')),
]

instructor/models.py
from django.db import models
from accounts.models import User


class Instructor(models.Model):
    """
    Instructors Profile
    """
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='instructor')
    photo = models.FileField(upload_to='tutor', null=True, blank=True)
    designation = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    course = models.ManyToManyField('course.Course')
    class Meta:
        verbose_name_plural = 'Instructor'

    def __str__(self):
        return self.user.username

instructor/views.py
# coding=utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from accounts.decorators import instructor_required
from course.models import Course
from quiz.forms import QuestionForm, BaseAnswerInlineFormSet, QuizCreateForm
from quiz.models import Quiz, Question, Answer




@method_decorator([login_required], name='dispatch')
class CourseDetailView(DetailView):
    model = Course
    context_object_name = 'course'
    template_name = 'take_course.html'
    pk_url_kwarg = 'course_pk'


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizListView(ListView):
    """
    Returns list of quiz created by the currently logged in tutor
    """
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'quiz_change_list.html'

    def get_queryset(self):
        """
        Overrides th default queryset method to return quizzes by the currently logged in user
        :return:
        """
        queryset = self.request.user.quizzes \
            .select_related('course') \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_quizzes', distinct=True))
        return queryset


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizCreateView(CreateView):
    """

    """
    form_class = QuizCreateForm
    template_name = 'quiz_add_form.html'
    success_url = reverse_lazy('instructor:quiz_change_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'instance': self.object, 'current_user': self.request.user})
            return kwargs

    def form_valid(self, form):
        quiz = form.save(commit=False)
        print("here")
        course = Course.objects.get(pk=self.kwargs['course_pk'])
        print(self.request.user, course.creator)
        quiz.owner = self.request.user
        quiz.course = course
        quiz.save()
        messages.success(self.request, 'The quiz was created with success! Go ahead and add some questions now.')
        return redirect('instructor:quiz_change_list')


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizUpdateView(UpdateView):
    model = Quiz
    fields = ('name', 'course', )
    context_object_name = 'quiz'
    template_name = 'quiz_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.quizzes.all()

    def get_success_url(self):
        return reverse('instructor:quiz_change', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        """
        Overiding the dispatch method to ensure that only the authr of a quiz can change it
        """
        obj = self.get_object()
        if obj.owner != self.request.user:
            messages.error(self.request, "You cant edit this quiz as you are not the author")
            return redirect('instructor:course_change_list')
        return super().dispatch(request)


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'quiz_delete_confirm.html'
    success_url = reverse_lazy('instructor:quiz_change_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@method_decorator([login_required, instructor_required], name='dispatch')
class QuizResultsView(DetailView):
    model = Quiz
    context_object_name = 'quiz'
    template_name = 'quiz_results.html'

    def get_context_data(self, **kwargs):
        quiz = self.get_object()
        taken_quizzes = quiz.taken_quizzes.select_related('student__user').order_by('-date')
        total_taken_quizzes = taken_quizzes.count()
        quiz_score = quiz.taken_quizzes.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_quizzes': taken_quizzes,
            'total_taken_quizzes': total_taken_quizzes,
            'quiz_score': quiz_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.quizzes.all()


@login_required
@instructor_required
def question_add(request, pk):
    # By filtering the quiz by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # quiz will be able to add questions to it.
    quiz = get_object_or_404(Quiz, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('instructor:question_change', quiz.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'question_add_form.html', {'quiz': quiz, 'form': form})


@login_required
@instructor_required
def question_change(request, quiz_pk, question_pk):
    # Simlar to the `question_add` view, this view is also managing
    # the permissions at object-level. By querying both `quiz` and
    # `question` we are making sure only the owner of the quiz can
    # change its details and also only questions that belongs to this
    # specific quiz can be changed via this url (in cases where the
    # user might have forged/player with the url params.
    quiz = get_object_or_404(Quiz, pk=quiz_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, quiz=quiz)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('instructor:quiz_change', quiz.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'question_change_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'formset': formset
    })


@method_decorator([login_required, instructor_required], name='dispatch')
class QuestionDeleteView(DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'question_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['quiz'] = question.quiz
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(request, 'The question %s was deleted with success!' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(quiz__owner=self.request.user)

    def get_success_url(self):
        question = self.get_object()
        return reverse('instructor:quiz_change', kwargs={'pk': question.quiz_id})

    def dispatch(self, request, *args, **kwargs):
        """
        Overiding the dispatch method to ensure that only the authr of a quiz can change it
        """
        obj = self.get_object()
        if obj.owner != self.request.user:
            messages.error(self.request, "You cant delete this quiz as you are not the author")
            return redirect('instructor:course_change_list')
        return super().dispatch(request)

instructor/templates/course_add_form.html
{% extends 'externals/base.html' %}

{% load crispy_forms_tags %}
          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom">Add a new Course</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'instructor:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>
            </div>
    </section>
{% endblock %}

instructor/templates/course_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Admin Dashboard</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
      <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'instructor:course_change_list' %}">My Courses</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ course_name }}</li>
    </ol>
  </nav>

  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>

      </form>
    </div>
  </div>

{% endblock %}

instructor/templates/course_change_list.html
{% extends 'externals/base.html' %}

          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Available Courses</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">


  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
            {% if request.user.is_instructor %}
          <th>Created</th>
            {% endif %}
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for course in courses %}
          <tr>
            {% if request.user.is_instructor %}
                 <td class="align-middle"><a href="{% url 'instructor:course_detail' course.pk %}">{{ course.title }}</a></td>
              {% elif reuest.user.is_student %}
                     <td class="align-middle"><a href="{% url 'student:course_detail' course.pk %}">{{ course.title }}</a></td>
                {% elif request.user.is_admin %}
                     <td class="align-middle"><a href="{% url 'instructor:course_detail' course.pk %}">{{ course.title }}</a></td>

                {% endif %}

            <td class="align-middle">{{ course.description|truncatechars:15}}</td>
              {% if request.user.is_instructor %}
            <td class="align-middle">{{ course.created }}</td>
              {% endif %}
            <td class="text-right">
                {% if request.user.is_instructor %}

              <a href="{% url 'instructor:quiz_add' course.pk %}" class="btn btn-primary">Create Quiz</a>

                    {% endif %}
            {% if request.user.is_student %}
{#              <a href="{% url 'student:register_course' course.pk %}" class="btn btn-primary">Register Course</a>#}
            {% endif %}
            </td>

          </tr>
        {% empty %}
            {% if request.user.is_instructor %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any course yet.</td>
          </tr>
            {% endif %}
            {% if request.user.is_student %}
            <tr>
                <td class="bg-light text-center font-italic" colspan="5">There are no course available.</td>
            </tr>
            {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
            </div>
    </section>
{% endblock %}

instructor/templates/course_delete_confirm.html
{% extends 'externals/base.html' %}

{% load crispy_forms_tags %}

          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom"> Confirm Delete</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the course <strong>"{{ course.title }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'instructor:course_change_list'%}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
            </div>
    </section>
{% endblock %}

instructor/templates/question_change_form.html
{% extends 'externals/base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}
         {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
      <li class="breadcrumb-item"><a href="{% url 'instructor:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'instructor:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>10</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'instructor:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    <a href="{% url 'instructor:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">Delete</a>
  </form>
            </div>
    </section>
{% endblock %}

instructor/templates/quiz_change_form.html
{% extends 'externals/base.html' %}

{% load crispy_forms_tags %}
         {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
      <li class="breadcrumb-item"><a href="{% url 'instructor:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'instructor:quiz_results' quiz.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'instructor:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a href="{% url 'instructor:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'instructor:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}

            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'instructor:question_add' quiz.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'instructor:question_add' quiz.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
            </div>
    </section>
{% endblock %}

instructor/templates/quiz_change_list.html
{% extends 'externals/base.html' %}

          {% block header %}
                   {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
            <div class="container-fluid">
              <h2 class="no-margin-bottom">My Quizzes</h2>
            </div>
          {% endblock header %}

    {% block content %}
    <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">

{#  <a href="{% url 'instructor:quiz_add' %}" class="btn btn-primary mb-3" role="button">Add quiz</a>#}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Course</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'instructor:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.course.title }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="text-right">
{#              <a href="{% url 'instructor:quiz_results' quiz.pk %}" class="btn btn-primary">View results</a>#}
                <a href="{% url 'instructor:quiz_change' quiz.pk %}" class="btn btn-primary">Edit Quiz</a>

            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any quiz yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
            </div>
    </section>
{% endblock %}

instructor/templates/quiz_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the quiz <strong>"{{ quiz.name }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}